name: Morning
on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: '10 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout 仓库a
      - uses: actions/checkout@v3

      # 2. 设置Node环境 安装npm
      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. 安装依赖
      - name: Install
        run: npm install

      # 4. 运行脚本
      - name: 运行脚本
        run: npm run start:morning
        env:
          WX_COMPANY_ID: ${{ secrets.WX_COMPANY_ID }}
          WX_APP_ID: ${{ secrets.WX_APP_ID }}
          WX_APP_SECRET: ${{ secrets.WX_APP_SECRET }}
          GAODE_API_KEY: ${{ secrets.GAODE_API_KEY }}